-- 테스트 데이터 정리 (외래키 순서 고려)
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE order_item;
TRUNCATE TABLE orders;
TRUNCATE TABLE coupon;
TRUNCATE TABLE coupon_policy;
TRUNCATE TABLE product;
TRUNCATE TABLE users;

SET FOREIGN_KEY_CHECKS = 1;

-- AUTO_INCREMENT 초기화 (MySQL 기준)
ALTER TABLE users AUTO_INCREMENT = 1;
ALTER TABLE product AUTO_INCREMENT = 1;
ALTER TABLE coupon_policy AUTO_INCREMENT = 1;
ALTER TABLE orders AUTO_INCREMENT = 1;
ALTER TABLE order_item AUTO_INCREMENT = 1;
ALTER TABLE coupon AUTO_INCREMENT = 1;